package com.gene.soeasy.entity.mybatis;

import java.util.ArrayList;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyidIsNull() {
            addCriterion("companyID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyidIsNotNull() {
            addCriterion("companyID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyidEqualTo(Integer value) {
            addCriterion("companyID =", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotEqualTo(Integer value) {
            addCriterion("companyID <>", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThan(Integer value) {
            addCriterion("companyID >", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("companyID >=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThan(Integer value) {
            addCriterion("companyID <", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThanOrEqualTo(Integer value) {
            addCriterion("companyID <=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidIn(List<Integer> values) {
            addCriterion("companyID in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotIn(List<Integer> values) {
            addCriterion("companyID not in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidBetween(Integer value1, Integer value2) {
            addCriterion("companyID between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotBetween(Integer value1, Integer value2) {
            addCriterion("companyID not between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanypidIsNull() {
            addCriterion("companyPID is null");
            return (Criteria) this;
        }

        public Criteria andCompanypidIsNotNull() {
            addCriterion("companyPID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanypidEqualTo(Integer value) {
            addCriterion("companyPID =", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidNotEqualTo(Integer value) {
            addCriterion("companyPID <>", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidGreaterThan(Integer value) {
            addCriterion("companyPID >", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidGreaterThanOrEqualTo(Integer value) {
            addCriterion("companyPID >=", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidLessThan(Integer value) {
            addCriterion("companyPID <", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidLessThanOrEqualTo(Integer value) {
            addCriterion("companyPID <=", value, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidIn(List<Integer> values) {
            addCriterion("companyPID in", values, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidNotIn(List<Integer> values) {
            addCriterion("companyPID not in", values, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidBetween(Integer value1, Integer value2) {
            addCriterion("companyPID between", value1, value2, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanypidNotBetween(Integer value1, Integer value2) {
            addCriterion("companyPID not between", value1, value2, "companypid");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNull() {
            addCriterion("companyName is null");
            return (Criteria) this;
        }

        public Criteria andCompanynameIsNotNull() {
            addCriterion("companyName is not null");
            return (Criteria) this;
        }

        public Criteria andCompanynameEqualTo(String value) {
            addCriterion("companyName =", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotEqualTo(String value) {
            addCriterion("companyName <>", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThan(String value) {
            addCriterion("companyName >", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameGreaterThanOrEqualTo(String value) {
            addCriterion("companyName >=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThan(String value) {
            addCriterion("companyName <", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLessThanOrEqualTo(String value) {
            addCriterion("companyName <=", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameLike(String value) {
            addCriterion("companyName like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotLike(String value) {
            addCriterion("companyName not like", value, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameIn(List<String> values) {
            addCriterion("companyName in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotIn(List<String> values) {
            addCriterion("companyName not in", values, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameBetween(String value1, String value2) {
            addCriterion("companyName between", value1, value2, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanynameNotBetween(String value1, String value2) {
            addCriterion("companyName not between", value1, value2, "companyname");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("companyCode is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("companyCode is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("companyCode =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("companyCode <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("companyCode >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("companyCode >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("companyCode <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("companyCode <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("companyCode like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("companyCode not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("companyCode in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("companyCode not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("companyCode between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("companyCode not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanydescIsNull() {
            addCriterion("companyDESC is null");
            return (Criteria) this;
        }

        public Criteria andCompanydescIsNotNull() {
            addCriterion("companyDESC is not null");
            return (Criteria) this;
        }

        public Criteria andCompanydescEqualTo(String value) {
            addCriterion("companyDESC =", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescNotEqualTo(String value) {
            addCriterion("companyDESC <>", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescGreaterThan(String value) {
            addCriterion("companyDESC >", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescGreaterThanOrEqualTo(String value) {
            addCriterion("companyDESC >=", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescLessThan(String value) {
            addCriterion("companyDESC <", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescLessThanOrEqualTo(String value) {
            addCriterion("companyDESC <=", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescLike(String value) {
            addCriterion("companyDESC like", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescNotLike(String value) {
            addCriterion("companyDESC not like", value, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescIn(List<String> values) {
            addCriterion("companyDESC in", values, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescNotIn(List<String> values) {
            addCriterion("companyDESC not in", values, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescBetween(String value1, String value2) {
            addCriterion("companyDESC between", value1, value2, "companydesc");
            return (Criteria) this;
        }

        public Criteria andCompanydescNotBetween(String value1, String value2) {
            addCriterion("companyDESC not between", value1, value2, "companydesc");
            return (Criteria) this;
        }

        public Criteria andIsgroupIsNull() {
            addCriterion("isGroup is null");
            return (Criteria) this;
        }

        public Criteria andIsgroupIsNotNull() {
            addCriterion("isGroup is not null");
            return (Criteria) this;
        }

        public Criteria andIsgroupEqualTo(Boolean value) {
            addCriterion("isGroup =", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupNotEqualTo(Boolean value) {
            addCriterion("isGroup <>", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupGreaterThan(Boolean value) {
            addCriterion("isGroup >", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isGroup >=", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupLessThan(Boolean value) {
            addCriterion("isGroup <", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupLessThanOrEqualTo(Boolean value) {
            addCriterion("isGroup <=", value, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupIn(List<Boolean> values) {
            addCriterion("isGroup in", values, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupNotIn(List<Boolean> values) {
            addCriterion("isGroup not in", values, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupBetween(Boolean value1, Boolean value2) {
            addCriterion("isGroup between", value1, value2, "isgroup");
            return (Criteria) this;
        }

        public Criteria andIsgroupNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isGroup not between", value1, value2, "isgroup");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table org_company
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 03 17:26:49 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}