package com.gene.soeasy.entity.mybatis;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept.deptID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept.deptName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private String deptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept.deptPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer deptpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept.companyID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_dept.deptDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private String deptdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_dept
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Dept(Integer deptid, String deptname, Integer deptpid, Integer companyid, String deptdesc) {
        this.deptid = deptid;
        this.deptname = deptname;
        this.deptpid = deptpid;
        this.companyid = companyid;
        this.deptdesc = deptdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_dept
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Dept() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept.deptID
     *
     * @return the value of org_dept.deptID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept.deptID
     *
     * @param deptid the value for org_dept.deptID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept.deptName
     *
     * @return the value of org_dept.deptName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept.deptName
     *
     * @param deptname the value for org_dept.deptName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept.deptPID
     *
     * @return the value of org_dept.deptPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getDeptpid() {
        return deptpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept.deptPID
     *
     * @param deptpid the value for org_dept.deptPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDeptpid(Integer deptpid) {
        this.deptpid = deptpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept.companyID
     *
     * @return the value of org_dept.companyID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept.companyID
     *
     * @param companyid the value for org_dept.companyID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_dept.deptDesc
     *
     * @return the value of org_dept.deptDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getDeptdesc() {
        return deptdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_dept.deptDesc
     *
     * @param deptdesc the value for org_dept.deptDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDeptdesc(String deptdesc) {
        this.deptdesc = deptdesc == null ? null : deptdesc.trim();
    }
}