package com.gene.soeasy.entity.mybatis;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.url
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer menupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private String menudesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.divider
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer divider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sortID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer sortid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Menu(Integer menuid, String menuname, String url, Integer menupid, String menudesc, Integer divider, Integer sortid) {
        this.menuid = menuid;
        this.menuname = menuname;
        this.url = url;
        this.menupid = menupid;
        this.menudesc = menudesc;
        this.divider = divider;
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Menu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuID
     *
     * @return the value of sys_menu.menuID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuID
     *
     * @param menuid the value for sys_menu.menuID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuName
     *
     * @return the value of sys_menu.menuName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuName
     *
     * @param menuname the value for sys_menu.menuName
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.url
     *
     * @return the value of sys_menu.url
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.url
     *
     * @param url the value for sys_menu.url
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuPID
     *
     * @return the value of sys_menu.menuPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getMenupid() {
        return menupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuPID
     *
     * @param menupid the value for sys_menu.menuPID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setMenupid(Integer menupid) {
        this.menupid = menupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuDesc
     *
     * @return the value of sys_menu.menuDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public String getMenudesc() {
        return menudesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuDesc
     *
     * @param menudesc the value for sys_menu.menuDesc
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setMenudesc(String menudesc) {
        this.menudesc = menudesc == null ? null : menudesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.divider
     *
     * @return the value of sys_menu.divider
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getDivider() {
        return divider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.divider
     *
     * @param divider the value for sys_menu.divider
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setDivider(Integer divider) {
        this.divider = divider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sortID
     *
     * @return the value of sys_menu.sortID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sortID
     *
     * @param sortid the value for sys_menu.sortID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }
}