package com.gene.soeasy.entity.mybatis;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.userID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.roleID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public UserRole(Integer id, Integer userid, Integer roleid) {
        this.id = id;
        this.userid = userid;
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public UserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.userID
     *
     * @return the value of sys_user_role.userID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.userID
     *
     * @param userid the value for sys_user_role.userID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.roleID
     *
     * @return the value of sys_user_role.roleID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.roleID
     *
     * @param roleid the value for sys_user_role.roleID
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}