package com.gene.soeasy.entity;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.id
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.menuID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public RoleMenu(Integer id, Integer roleid, Integer menuid) {
        this.id = id;
        this.roleid = roleid;
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public RoleMenu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.id
     *
     * @return the value of sys_role_menu.id
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.id
     *
     * @param id the value for sys_role_menu.id
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.roleID
     *
     * @return the value of sys_role_menu.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.roleID
     *
     * @param roleid the value for sys_role_menu.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.menuID
     *
     * @return the value of sys_role_menu.menuID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.menuID
     *
     * @param menuid the value for sys_role_menu.menuID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}