package com.gene.soeasy.entity;


public class User {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.userID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.userCode
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.userName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.userPWD
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.userStatus
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer userstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.logInfo
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String loginfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public User(Integer userid, String usercode, String username, String userpwd, Integer userstatus, String loginfo) {
        this.userid = userid;
        this.usercode = usercode;
        this.username = username;
        this.userpwd = userpwd;
        this.userstatus = userstatus;
        this.loginfo = loginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.userID
     *
     * @return the value of sys_user.userID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.userID
     *
     * @param userid the value for sys_user.userID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.userCode
     *
     * @return the value of sys_user.userCode
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.userCode
     *
     * @param usercode the value for sys_user.userCode
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.userName
     *
     * @return the value of sys_user.userName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.userName
     *
     * @param username the value for sys_user.userName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.userPWD
     *
     * @return the value of sys_user.userPWD
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.userPWD
     *
     * @param userpwd the value for sys_user.userPWD
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.userStatus
     *
     * @return the value of sys_user.userStatus
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.userStatus
     *
     * @param userstatus the value for sys_user.userStatus
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setUserstatus(Integer userstatus) {
        this.userstatus = userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.logInfo
     *
     * @return the value of sys_user.logInfo
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getLoginfo() {
        return loginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.logInfo
     *
     * @param loginfo the value for sys_user.logInfo
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setLoginfo(String loginfo) {
        this.loginfo = loginfo == null ? null : loginfo.trim();
    }
}