package com.gene.soeasy.mapper.mybatis;

import com.gene.soeasy.entity.mybatis.Company;
import com.gene.soeasy.entity.mybatis.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int deleteByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int insert(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int insertSelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    Company selectByPrimaryKey(Integer companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByExampleSelective(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByExample(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByPrimaryKeySelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByPrimaryKey(Company row);
}