package com.gene.soeasy.mapper.mybatis;

import com.gene.soeasy.entity.mybatis.RoleMenu;
import com.gene.soeasy.entity.mybatis.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    long countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int insert(RoleMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int insertSelective(RoleMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByExampleSelective(@Param("row") RoleMenu row, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByExample(@Param("row") RoleMenu row, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByPrimaryKeySelective(RoleMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Sat Sep 03 17:26:49 CST 2022
     */
    int updateByPrimaryKey(RoleMenu row);
}