package com.gene.soeasy.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleDesc
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    private String roledesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Role(Integer roleid, String rolename, String roledesc) {
        this.roleid = roleid;
        this.rolename = rolename;
        this.roledesc = roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleID
     *
     * @return the value of sys_role.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleID
     *
     * @param roleid the value for sys_role.roleID
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleName
     *
     * @return the value of sys_role.roleName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleName
     *
     * @param rolename the value for sys_role.roleName
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleDesc
     *
     * @return the value of sys_role.roleDesc
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleDesc
     *
     * @param roledesc the value for sys_role.roleDesc
     *
     * @mbg.generated Mon Aug 29 17:17:09 CST 2022
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc == null ? null : roledesc.trim();
    }
}